name: continuous-integration-foo

on:
    push:
        branches:
            - master

jobs:
    build-and-test:
        runs-on:  ubuntu-latest
        steps:
            - uses: actions/checkout@v1

            - name: Set up JDK 1.8
              uses: actions/setup-java@v1
              with:
                  java-version: 1.8

            - name: Build with Gradle!
              working-directory: .
              run: ./gradlew build -x test

            - name: Run Gradle tests
              working-directory: .
              run: ./gradlew test

    integration-test:
        runs-on: ubuntu-latest
        needs: build-and-test
        steps:
            - uses: actions/checkout@v1

            - name: Start up containers
              working-directory: .
              run: docker-compose up -d --build
                  
            - name: Install Python dependencies
              working-directory: .
              run: pip install pytest requests
            
            - name: Run system tests
              working-directory: .
              run: pytest

            - name: Purge containers
              working-directory: .
              run: docker-compose down



